# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Position Controllers ---------------------------------------
torso_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: torso_joint
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_l_s_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_l_s
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_l_l_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_l_l
  pid: {p: 1000, i: 500, d: 0, i_clamp: 500}
joint_l_e_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_l_e
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_l_u_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_l_u
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_l_r_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_l_r
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}
joint_l_b_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_l_b
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}  
joint_l_t_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_l_t
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50    
joint_r_s_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_r_s
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_r_l_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_r_l
  pid: {p: 1000, i: 500, d: 0, i_clamp: 500}
joint_r_e_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_r_e
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_r_u_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_r_u
  pid: {p: 100, i: 10, d: 0, i_clamp: 100}
joint_r_r_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_r_r
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}
joint_r_b_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_r_b
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}  
joint_r_t_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_r_t
  pid: {p: 10, i: 1, d: 0, i_clamp: 100}


# Trajectory Controllers
larm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_l_s
    - joint_l_l
    - joint_l_e
    - joint_l_u
    - joint_l_r
    - joint_l_b
    - joint_l_t
  gains:
    joint_l_s: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_l_l: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_l_e: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_l_u: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_l_r: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_l_b: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_l_t: {p: 50, i: 200, d: 0, i_clamp: 0}

rarm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_r_s
    - joint_r_l
    - joint_r_e
    - joint_r_u
    - joint_r_r
    - joint_r_b
    - joint_r_t
  gains:
    joint_r_s: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_r_l: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_r_e: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_r_u: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_r_r: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_r_b: {p: 50, i: 200, d: 0, i_clamp: 0}
    joint_r_t: {p: 50, i: 200, d: 0, i_clamp: 0}

torso_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - torso_joint
  gains:
    torso_joint: {p: 50, i: 200, d: 0, i_clamp: 0}    
