sia5:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  
  sia5_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - joint_s
      - joint_l
      - joint_e
      - joint_u
      - joint_r
      - joint_b
      - joint_t
    
    gains: # Required because we're controlling an effort interface
      joint_s: {p: 100.0, i: 10.0, d: 0.0, i_clamp: 100.0}
      joint_l: {p: 1000.0, i: 500.0, d: 0.0, i_clamp: 500.0}
      joint_e: {p: 100.0, i: 10.0, d: 0.0, i_clamp: 100.0}
      joint_u: {p: 100.0, i: 10.0, d: 0.0, i_clamp: 100.0}
      joint_r: {p: 10.0, i: 1.0, d: 0.0, i_clamp: 100.0}
      joint_b: {p: 10.0, i: 1.0, d: 0.0, i_clamp: 100.0}
      joint_t: {p: 10.0, i: 1.0, d: 0.0, i_clamp: 100.0}
