sia5:
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
brazo_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_s
    - joint_l
    - joint_e
    - joint_u
    - joint_r
    - joint_b
    - joint_t

gains: # Required because we're controlling an effort interface
  joint_s: {p: 1.0, i: 0.6, d: 0.3}
  joint_l: {p: 1.0, i: 0.6, d: 0.3}
  joint_e: {p: 1.0, i: 0.6, d: 0.3}
  joint_u: {p: 1.0, i: 0.6, d: 0.3}
  joint_r: {p: 1.0, i: 0.6, d: 0.3}
  joint_b: {p: 1.0, i: 0.6, d: 0.3}
  joint_t: {p: 1.0, i: 0.6, d: 0.3}
